### ISSUE TITLE
Files missing

### ISSUE THREAD

**Issue by nramsbottom** [DKorablin/DeviceIoControl#1]
The files LogicalDrive.cs and PinnedBufferReader.cs in the DeviceIoControl project appear to be missing. The latter is a reference to a file in a directory named "FileReader".

**Comment by DKorablin** [comment]
Missing files added:
https://github.com/DKorablin/DeviceIoControl/blob/master/DeviceIoControl/LogicalDrive.cs
https://github.com/DKorablin/DeviceIoControl/blob/master/DeviceIoControl/PinnedBufferReader.cs
